### ISSUE TITLE
Angedrohter Bombenanschlag war am 01.08.2015, nicht 2016

### ISSUE THREAD

**Issue by gka** [ax3l/chronik-vorfaelle#1]
![image](https://cloud.githubusercontent.com/assets/617518/12960215/1728d2c4-d008-11e5-8de8-8581be329be1.png)

**Comment by ax3l** [comment]
Vielen Dank für den Hinweis, das ist ein Tippfehler. Ich leite dies gleich weiter an die Verantwortlichen für die [Chronik](https://www.mut-gegen-rechte-gewalt.de/service/chronik-vorfaelle) zur Berichtigung.

Habe den Screenshot auch kurz nochmal in der angegebenen [Quelle](http://www.linksfraktion-berlin.de/uploads/media/S17-17661.pdf) gegengeprüft.

**Comment by ax3l** [comment]
Der Eintrag wurde in der Chronik korrigiert (vielen Dank noch einmal für den Hinweis) und der Datenexport hier wurde mit f1756c8836dab6a3eeba9bc9791815ce1773ec5b aktualisiert.
