### ISSUE TITLE
Umwandlung zu CSV

### ISSUE THREAD

**Issue by lukaskawerau** [ax3l/chronik-vorfaelle#2]
Hi @ax3l,

habe den Scraper eben mal bei mir laufen lassen, funktionierte wunderbar.
Leider fehlt ein Tool zur Konvertierung zu CSV, obwohl im data branch ja eine csv vorhanden ist.
Wie machst du das?

**Comment by ax3l** [comment]
Hi @lukaskawerau,

die aktuellen Date lade ich regelmäßig in den `data` branch hoch, falls du etwas Last bei openstreetmaps und auf der Homepage der Amadeu Antonio Stiftung vermeiden willst lade die lieber von GitHub herunter ;)

Zum Konvertieren nehme ich einfach https://github.com/vinay20045/json-to-csv und führe lokal:

``` bash
python json_to_csv.py features data/vorfaelle.geojson data/vorfaelle.csv
```

aus.

Meine Ordnerstruktur ist etwas verschachtelter, daher ist der (noch) nicht eingecheckt. Ich update via

``` bash
#!/usr/bin/env bash
#

# scrape data
cd scraper/chronikScraper
scrapy crawl chronikScraper
cd -

# mv data
mv scraper/chronikScraper/vorfaelle.geojson data/

# remove EOL white spaces
sed -i 's/ *$//' data/vorfaelle.geojson

# convert data to CSV
#   https://github.com/vinay20045/json-to-csv
python json_to_csv.py features data/vorfaelle.geojson data/vorfaelle.csv
```

**Comment by lukaskawerau** [comment]
Ah cool, danke dir!

Die Daten waren jetzt nen Monat alt, deswegen war ich so frech und hab's einfach mal selber ausprobiert ;)
Außerdem ist mir aufgefallen, dass es mit openstreetmaps einige GEOMISS gab, habe deshalb auf GoogleV3 umgestellt, da gab es dann keine mehr. Die Last bei der Stiftung ist natürlich etwas, das es zu reduzieren gilt.

Jedenfalls vielen Dank, dass du die Daten und den Scraper teilst! 👍

**Comment by ax3l** [comment]
Gerne, habs auch gleich zum Anlass genommen wieder den Importer anzuwerfen ;) Updated :)

kannst ja mal deinen diff zeigen, brauch ich für GoogleV3 nen API key?

**Comment by lukaskawerau** [comment]
Genau, GoogleV3 braucht nen API key. 2500 requests/tag umsonst, danach $0.5/1000 weitere.

Diff: Nominatim == GoogleV3, fertig :)
